cargo-features = ["edition2024"]
[package]
name = "ambient-auction-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ambient-auction-api = { git = "https://github.com/ambient-xyz/auction-api", rev = "1745a8b0b24f6aaab2093718e64e444d4be32711" }
lz4_flex = "0.11.6"
solana-sdk = "2.3.1"
solana-system-interface = "1.0.0"
solana-vote-interface = "2.2.6"

[features]
global-config = ["ambient-auction-api/global-config"]
default = []

[dev-dependencies]
solana-ed25519-program = "2.2.3"
bincode = "1.3.3"
