cargo-features = ["edition2024"]
[package]
name = "ambient-auction-client"
version = "0.1.0"
edition = "2024"

[dependencies]
ambient-auction-api = { git = "https://github.com/ambient-xyz/auction-api", rev = "6b29c86fba48c233517583908dcb4c775aab50ae" }
lz4_flex = "0.11.6"
solana-sdk = "2.3.1"
solana-system-interface = "1.0.0"
solana-vote-interface = "2.2.6"

[features]
default = []

[dev-dependencies]
solana-ed25519-program = "2.2.3"
bincode = "1.3.3"
